### ISSUE TITLE
split trailing match

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#13]
If you do a simple split with TFLRE.Create('#', []), both 'a' and 'a#' split to the same single element array ['a']. so you cannot join it back together to get the original input. I think the latter should give ['a', '']

**Comment by BeRo1985** [comment]
Okay, I'll try to fix that in the next minutes or hours.

**Comment by BeRo1985** [comment]
Changed/improved in lastest commit, but keep it in mind, that FLRE's Split behaviour is now like ECMAScript/JavaScript's String.split and not PHP's preg_split. 

So a empty regex doesn't split the input string char-wise into single chars, but as PHP preg_split would do it, and ECMAScript/JavaScript's String.split not, ECMAScript/JavaScript's String.split (like FLRE) would return the whole input string in this case.

**Comment by benibela** [comment]
So now it is supposed to insert the captures in the splitted array ? That is not what I need either :(

**Comment by BeRo1985** [comment]
For example:

splitting a#b#c#d by regex # => ['a','b','c','d']
splitting a#b-c#d- by regex #(\w*)- => ['a','b','c','d']

Just read your favorite ECMAScript/JavaScript reference on the String.split() topic, because the FLRE split function works nearly exactly like ECMAScript/JavaScript's String.split(). 

And when you don't use capture groups or when you do use just non-capturing (?:) groups, then the FLRE split function act also similiar like PHP's preg_split or any another 08/15 split function in any other framework or language ecosystem.

**Comment by benibela** [comment]
> splitting a#b-c#d- by regex #(\w*)- => ['a','b','c','d']

 splitting a#b-c#d- by regex #(\w*)- => ['a','b','c','d', '']

>Just read your favorite ECMAScript/JavaScript reference on the String.split() topic, because the FLRE split function works nearly exactly like ECMAScript/JavaScript's String.split(). 

But I need XQuery's tokenize
