### ISSUE TITLE
start of empty capture

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#18]
If you match 'ab(c?)' to 'ab', the capture group starts at 2 with length 0.

Should it not be 3, since you can use `copy(input, start, length)` to get the captured text, so a start of 2, includes the character 2 and is thus on the left side of character 2. But `c?` should always be on the right side of the `b`.

(I need to split the input into something like `<group0>ab<group1></group1></group0>` which requires to find an ordering of all the capture groups. If the `c` were there, it had a start of 3 and the split was `<group0>ab<group1>c</group1></group0>`. Now with a start of 2, it `<group1/>` appears to move one character to the left and is on the wrong side )

**Comment by benibela** [comment]
Even worse for me, it seems impossible to distinguish empty ()() from (()) given only the match positions

**Comment by BeRo1985** [comment]
The first thing should work correctly now, but the second thing is very difficult or even impossible to implement in a pure non-backtracking every-single-char-will-just-once-processed-TNFA/DFA-based regular expression engine, because (()) are two zero-width NOP instructions inside nested capture-groups, where the TNFA/DFA algorithms don't increment their current input char position counters after the first zero-width NOP instruction.
