### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#20]
With fpc's heaptrc unit we can measure a baseline memory usage:

```
program Project1;
{$mode objfpc}{$H+}
uses heaptrc, FLRE;
var f: TFLRE;
begin
  f := TFLRE.Create('foobar',[]);
end.
```

and get 9223, almost 10kb. 

That is quite a lot for a simple 6 byte search pattern. An overhead of 153 700 % (it is even worse  with caching and using it for many tiny regexs on smartphones)

Improvements to consider:

* Have a flag for speed vs. memory. And do not do anything fancy for low memory usage. Just calling pos could be sufficient for foobar in many cases. Or automatically detect, if the speed up from the precomputation is  worth the memory usage . 

* Half of the memory usage is the TFLRE class itself. Move everything that is not always needed to some class that gives a nil pointer if not used. 

* Replace the longbool with enums in some set

* Every TFLRECharPatternBitMasks eats 1kb. Perhaps it can use byte/word instead longword for  small regexs? And for you probably do not need a value for every character . Only storing a subrange of the array for characters in the regex,  lowestOccuringChar..highestOccuringChar, would already help a lot. Many queries are ascii only

**Comment by BeRo1985** [comment]
TFLRECharPatternBitMasks must be 32-bit-wise because the underlying Boyer-Moore and SBNDMQ* algorithm implementations relies on this fact, since they are working 32-bit mask wise (for max. 32 char patterns, 1 bit = 1 char). 

Extend it for smaller bitmask sizes (in more function variants) would have a negative impact on the performance, and that would not be worth it.

But I've added PFLRECharPatternBitMasks now, so that that memory will be only allocated, when it's needed.

**Comment by BeRo1985** [comment]
And I've replaced the longbools with set-enums inside TFLRE now.
