### ISSUE TITLE
Warnings in a Delphi XE2 project

### ISSUE THREAD

**Issue by rchastain** [BeRo1985/flre#26]
This isn't really an issue. I would like to have an advice. Look at the following code. I first compiled it with FPC. When I included it in a Delphi XE2 project, I got many warnings about "implicit string cast". To get rid of the warnings, I added many "string(...)" and "TFLRERawByteString(...)".

My question is : is it useful to do that ? Is it safe ? Is there another way to solve that problem ?

[main.zip](https://github.com/BeRo1985/flre/files/183842/main.zip)

**Comment by rchastain** [comment]
I don't if what I said is clear enough. The warnings are raised by my code, not by FLRE code. That's why I said it isn't really an issue.

**Comment by BeRo1985** [comment]
Newer Delphi versions breaks code compatibility to old code, where `string` is no longer equals to `ansistring`, so the warnings are normal.  You can turn this specific warning off with `{$WARN IMPLICIT_STRING_CAST OFF}` and `{$WARN IMPLICIT_STRING_CAST_LOSS OFF}`, since it's just a reminder, and most of the time your program works fine, even with a little worse performance then, due to the internal back and forth string type variant conversions (for example ansistring -> unicodestring/widestring/localcodepagestring/etc. (<- system locale dependent) -> ansistring etc.).  

FreePascal does on the other hand (in my opinion) the right way and doesn't break code compatibility (except in the `{$mode delphiunicode}` mode, which tries to emulate then the (in my opinion bad and code compatibility breaking) behavior of the newer Delphi versions)

**Comment by rchastain** [comment]
Thank you for that very useful answer.
