### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#7]
I tried to figure out how to use it, but did not get far. 

Starting simple:

     f := TFLRE.Create('oder');

=> Exception: Invalid regular expression

Well, I need to set flags anyways

    f := TFLRE.Create('oder', []);
    f.Match('modern', captures);

=> captures = ({START = 0, LENGTH = 0})  

nothing found?

Perhaps it needs a flag?

    f := TFLRE.Create('oder', [rfMULTIMATCH]);
    f.Match('modern', captures);

=> captures = ({START = 0, LENGTH = 0}, {START = 0, LENGTH = 0})  

now it finds more, but still nothing.

**Comment by BeRo1985** [comment]
1. `f := TFLRE.Create('oder');` is wrong, you do need here to write `f := TFLRE.Create('/oder/');` because FLRE is here in /pattern/modifiers parsing mode then, when there is no second parameter in the Create constructor, where "pattern" is the regular expression itself, and "modifiers" are a series of characters indicating various options.

2. And instead `f.Match('modern', captures);` you do need to use `f.MatchAll('modern', multiCaptures);` because Match does only a anchored search, and MatchAll does also a unanchored. Otherwise you do need a regex like *.(oder) if you do want still to use Match instead MatchAll, but then the speed optimizations will be undermined in this case.

**Comment by benibela** [comment]
That is not well documented

>Otherwise you do need a regex like *.(oder) if you do want still to use Match instead MatchAll, but then the speed optimizations will be undermined in this case.

But I only need to extract first match, getting all would be slower. With the modified regex it will make a copy of the entire prefix, will it not? That can be quite slow

**Comment by BeRo1985** [comment]
Just use MatchAll with a find limit value of 1. Then MatchAll stops after the first positive match.

**Comment by BeRo1985** [comment]
`function MatchAll(const Input:TFLRERawByteString;var MultiCaptures:TFLREMultiCaptures;const StartPosition:longint=1;Limit:longint=-1):boolean;`

Example: `MatchAll(Input, MultiCaptures, 1, 1);`

**Comment by benibela** [comment]
oh, i missed that option
