### ISSUE TITLE
PtrPosChar not working with \x00 at 8*i position

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#83]
PtrPosChar does not seem to work with \x00

There is `     while (XoredChunk<>0) and ((XoredChunk and $ff)<>TFLREUInt8(SearchChar)) do begin`, so if it is found, we have `(XoredChunk and $ff)` = `0`, and if it is the last byte in the chunk, it follows  `XoredChunk` = 0, so the function ignores it

Thus

```
var
  f: TFLRE;
  captures: TFLREMultiCaptures;
  i: Integer;
begin
  f := TFLRE.Create('\x00', []);
  f.UTF8MatchAll('abcdefg'#00'b'#00'c', captures);
  for i := 0 to high(captures) do writeln(captures[i][0].Start, ' ',captures[i][0].Length);

```

does not find the first #00

**Comment by Reino17** [comment]
@BeRo1985 If you have abandoned your `flre` project, then please add a statement on the frontpage. If not, then... well, I think it's kinda rude leaving all those who started an "issue"/bug-report here in the dark, not even leaving a single reply.

**Comment by BeRo1985** [comment]
No, I have not given up FLRE, however I am currently busy with other stuff until the end of March 2022, which is also where my notice period is with my employer. After that I will be self-employed, and where I will have more time for projects like FLRE again. That's why I quit my current job, to be able to manage my time better from end of March 2022 on.

**Comment by Reino17** [comment]
Alright. Thanks for the quick reply and your honesty.
