### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by benibela** [BeRo1985/flre#9]
This extraordinary pointless expression nearly killed my X server:

    a{2147483647}

**Comment by BeRo1985** [comment]
It's by design, because FLRE is using primarly non-backtracking algorithms, and these needs expanded regexs, for example the regex compiler expands a{5} to aaaaa. See quote from https://swtch.com/~rsc/regexp/regexp1.html :

>Many regular expression implementations provide a counted repetition operator {n} to match exactly n
>strings matching a pattern; {n,m} to match at least n but no more than m; and {n,} to match n or more. 
>A recursive backtracking implementation can implement counted repetition using a loop; an NFA or 
>DFA-based implementation must expand the repetition: e{3} expands to eee; e{3,5} expands to eeee?
>e?, and e{3,} expands to eee+.

All I could do about it, would be to implement a limit, for example a maximum limit 4096, 65536 or so.

**Comment by BeRo1985** [comment]
Introduced global FLREMaximalRepetitionCount variable for to avoid memory-wasting vulnerabilities (default value 4096) in lastest commit
